[project]
name = 'Blockchain-Based-Customer-Success-Account-Management-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.health-monitoring]
path = 'contracts/health-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.success-manager-verification]
path = 'contracts/success-manager-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
